In [1]:
# Convert The Below list into numpy then display array

In [3]:
import numpy as np
my_list=[1,2,3,4,5]
arr=np.array(my_list)
print(arr)

[1 2 3 4 5]


In [4]:
#Convert the below list into a numpy then display the arry then display the first and last index and then multiply each element by 2 and display the result

In [5]:
import numpy as np
my_list=[1,2,3,4,5]
arr=np.array(my_list)
print("First Element ",arr[0])
n=len(arr)
print("Last Element",arr[n-1])
print("Array after Doubling the element ",arr*2)

First Element  1
Last Element 5
Array after Doubling the element  [ 2  4  6  8 10]


In [6]:
#*************************************************************************LAB 3***********************************************************************


In [7]:
#Write a NumPy program to create a array of 10 zeros,10 ones,10 fives

In [8]:
import numpy as np
arr=np.zeros(10)
print("An Array of 10 Zeros",arr)
arr=np.ones(10)
print("An Array of 10 Zeros",arr)
arr=np.ones(10)*5
print("An Array of Fives",arr)

An Array of 10 Zeros [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An Array of 10 Zeros [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An Array of Fives [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [9]:
#Write a NumPy program to create a 3x3 matrix with values from 2 to 10

In [10]:
import numpy as np
arr1=np.arange(2,11).reshape(3,3)
print(arr1)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
